---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Chart validations
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
  - ../_values/advanced_mounts_invalid_component.yaml
tests:
  - it: advancedMounts invalid component reference should fail
    asserts:
      - failedTemplate:
          errorMessage: "No enabled component found with this identifier. (persistence item: 'data', component: 'test')"

  - it: advancedMounts set to null with invalid component reference should pass
    set:
      persistence:
        data:
          advancedMounts:
            test: null
    asserts:
      - notFailedTemplate: {}
