---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: component statefulset minReadySeconds
templates:
  - common.yaml
values:
  - ../_values/components_main_default_container.yaml
tests:
  # StatefulSet
  - it: setting minReadySeconds should pass for StatefulSet
    set:
      components.main:
        type: statefulset
        statefulset:
          minReadySeconds: 15
    asserts:
      - documentIndex: 0
        isKind:
          of: StatefulSet
      - documentIndex: 0
        equal:
          path: spec.minReadySeconds
          value: 15
  - it: default minReadySeconds should pass for StatefulSet
    set:
      components.main:
        type: statefulset
    asserts:
      - documentIndex: 0
        isKind:
          of: StatefulSet
      - documentIndex: 0
        notExists:
          path: spec.minReadySeconds
